import 'dotenv/config'
import { parseArgs } from 'node:util'
import { hashPassword } from './crypto.ts'
import { createPrisma } from './db.ts'

// Bootstraps the whole chain. Access is invite-only and invites can only be
// generated by an admin of an existing workspace, so without this there is no
// first workspace, no first admin, and no way in at all.
//
//   pnpm --filter @idea/core seed:admin \
//     --username admin01 --password '...' --workspace '默认空间'

const { values } = parseArgs({
  options: {
    username: { type: 'string' },
    password: { type: 'string' },
    workspace: { type: 'string' },
    name: { type: 'string' },
  },
})

const { username, password, workspace, name } = values

if (!username || !password || !workspace) {
  console.error('usage: seed:admin --username <u> --password <p> --workspace <w> [--name <n>]')
  process.exit(1)
}

// Deliberately not using normalizeUsername from @idea/shared here: core must not
// depend on shared for one function, and the seed operator is trusted to pass a
// sane value. The server enforces the full rules on every other path.
const normalized = username.trim().toLowerCase()

const url = process.env.DATABASE_URL
if (!url) {
  console.error('DATABASE_URL is not set')
  process.exit(1)
}

const [prisma, disconnect] = createPrisma(url)

try {
  const existing = await prisma.user.findUnique({ where: { username: normalized } })
  if (existing) {
    console.error(`user "${normalized}" already exists — nothing done`)
    process.exit(1)
  }

  // One transaction: a half-seeded state (user with no workspace, or a workspace
  // nobody administers) is worse than a clean failure, because the operator
  // would have to diagnose it by hand before retrying.
  const result = await prisma.$transaction(async tx => {
    const user = await tx.user.create({
      data: {
        username: normalized,
        name: name ?? normalized,
        passwordHash: hashPassword(password),
      },
    })
    await tx.platformAdmin.create({ data: { userId: user.id } })
    const ws = await tx.workspace.create({ data: { name: workspace } })
    await tx.userWorkspace.create({
      data: { userId: user.id, workspaceId: ws.id, role: 'admin' },
    })
    return { user, ws }
  })

  console.log(`created user "${result.user.username}" (id ${result.user.id})`)
  console.log(`  platform admin: yes — may create workspaces`)
  console.log(`  workspace "${result.ws.name}" (id ${result.ws.id}), role admin`)
} finally {
  await disconnect()
}
